// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCPcq-fpSxaLnnq4T5s_19vem0fIVuI11Q",
    authDomain: "jurislink-app.firebaseapp.com",
    projectId: "jurislink-app",
    storageBucket: "jurislink-app.firebasestorage.app",
    messagingSenderId: "969711743833",
    appId: "1:969711743833:web:35a746c1c4c68c9e1e1248",
    measurementId: "G-S7G14B5T35",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYhAD-NA5fr_xayommEg9vGP0WyuqGLqM',
    appId: '1:969711743833:android:12db52dbd2114b941e1248',
    messagingSenderId: '969711743833',
    projectId: 'jurislink-app',
    storageBucket: 'jurislink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNrwozFX8otvrY8q4QITRZJ8WgS2wdAY',
    appId: '1:969711743833:ios:266555a6cb1374ac1e1248',
    messagingSenderId: '969711743833',
    projectId: 'jurislink-app',
    storageBucket: 'jurislink-app.firebasestorage.app',
    iosBundleId: 'com.example.jurislinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYyC2mmZjzo_ZE7zp4y8nC34yZzBxW38',
    appId: '1:591244992005:ios:a77eeb15e46a0f719b466c',
    messagingSenderId: '591244992005',
    projectId: 'techgen-60861',
    storageBucket: 'techgen-60861.firebasestorage.app',
    iosBundleId: 'com.example.techgenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    apiKey: "AIzaSyCPcq-fpSxaLnnq4T5s_19vem0fIVuI11Q",
    authDomain: "jurislink-app.firebaseapp.com",
    projectId: "jurislink-app",
    storageBucket: "jurislink-app.firebasestorage.app",
    messagingSenderId: "969711743833",
    appId: "1:969711743833:web:32c74712f073e5f51e1248",
    measurementId: "G-DSL90QDGH9",
  );
}
